export default function () {
  return [
    {
      id: Math.random(),
      index: 0,
      guid: '_' + Math.random().toString(36).substr(2, 9),
      isActive: true,
      balance: '_' + Math.random().toString(36).substr(2, 9),
      picture: '_' + Math.random().toString(36).substr(2, 9),
      age: 22,
      eyeColor: '_' + Math.random().toString(36).substr(2, 9),
      name: '_' + Math.random().toString(36).substr(2, 9),
      gender: '_' + Math.random().toString(36).substr(2, 9),
      company: '_' + Math.random().toString(36).substr(2, 9),
      email: 'marciefischer@ecratic.com',
      phone: '+1 (898) 521-2820',
      address: '313 Bulwer Place, Chemung, Montana, 266',
      about:
        'Enim dolore eiusmod ad excepteur cillum enim magna mollit eiusmod ad aliquip. Ipsum fugiat qui occaecat duis fugiat cillum reprehenderit mollit. In officia aliqua nulla dolor occaecat laborum aliqua non anim mollit laborum elit. Amet do ipsum sunt amet incididunt. Ex anim ex reprehenderit proident commodo nostrud deserunt enim eu ex ex nostrud occaecat. Laborum reprehenderit commodo ut aute duis proident excepteur aliquip aute consequat.\r\n',
      registered: '2017-09-10T07:06:18 -02:00',
      latitude: 44.566858,
      longitude: -95.515994,
      tags: [
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
      ],
      friends: [
        {
          id: 0,
          name: 'Willa Bernard',
        },
        {
          id: 1,
          name: 'Tommie Morris',
        },
        {
          id: 2,
          name: 'Lynda Moss',
        },
      ],
      greeting: 'Hello, Marcie Fischer! You have 5 unread messages.',
      favoriteFruit: '_' + Math.random().toString(36).substr(2, 9),
    },
    {
      id: Math.random(),
      index: 1,
      guid: 'd087abcd-2e8f-479c-ba1d-edb630006164',
      isActive: false,
      balance: '$1,980.12',
      picture: 'http://placehold.it/32x32',
      age: 29,
      eyeColor: '_' + Math.random().toString(36).substr(2, 9),
      name: 'Kaufman Lowe',
      gender: '_' + Math.random().toString(36).substr(2, 9),
      company: '_' + Math.random().toString(36).substr(2, 9),
      email: 'kaufmanlowe@ozean.com',
      phone: '+1 (944) 467-2726',
      address: '170 Hubbard Street, Nettie, Maine, 3275',
      about:
        'Lorem esse deserunt et incididunt occaecat adipisicing ea minim. Mollit qui cupidatat culpa eiusmod esse incididunt ut sint sunt laborum ullamco culpa elit nulla. Et eu deserunt ex mollit esse consequat sint deserunt sit mollit commodo. Eu tempor et dolore elit eiusmod eiusmod anim irure est exercitation laborum labore in. Lorem est ut sint culpa sint voluptate. Ullamco anim id nulla duis officia occaecat culpa tempor eiusmod ut. Qui exercitation consequat fugiat proident deserunt.\r\n',
      registered: '2020-04-13T02:29:22 -02:00',
      latitude: -75.087824,
      longitude: 102.896712,
      tags: [
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
      ],
      friends: [
        {
          id: Math.random(),
          name: 'Olson Hyde',
        },
        {
          id: Math.random(),
          name: 'Durham Miles',
        },
        {
          id: Math.random(),
          name: 'Emily Gutierrez',
        },
      ],
      greeting: 'Hello, Kaufman Lowe! You have 9 unread messages.',
      favoriteFruit: '_' + Math.random().toString(36).substr(2, 9),
    },
    {
      id: Math.random(),
      index: 2,
      guid: 'f8d4156f-d9bd-4da6-bc54-6dcc2fd6d3e1',
      isActive: true,
      balance: '$1,823.49',
      picture: 'http://placehold.it/32x32',
      age: 40,
      eyeColor: '_' + Math.random().toString(36).substr(2, 9),
      name: 'Sara Clark',
      gender: '_' + Math.random().toString(36).substr(2, 9),
      company: '_' + Math.random().toString(36).substr(2, 9),
      email: 'saraclark@gallaxia.com',
      phone: '+1 (832) 516-3157',
      address: '538 Cobek Court, Brantleyville, Marshall Islands, 6728',
      about:
        'Adipisicing commodo pariatur irure cillum culpa occaecat labore cillum eiusmod ad. Cillum eu sit incididunt commodo. Proident nostrud labore ipsum reprehenderit et non ullamco. Nulla anim anim labore consectetur cillum dolore cupidatat ipsum. Cillum proident consectetur ut id deserunt labore anim officia ipsum irure anim non do. Reprehenderit voluptate dolor eiusmod laborum duis laborum ullamco. Duis minim irure nulla nisi mollit eiusmod amet veniam ipsum officia dolore quis.\r\n',
      registered: '2016-07-30T01:45:43 -02:00',
      latitude: -32.45783,
      longitude: 53.736693,
      tags: [
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
        '_' + Math.random().toString(36).substr(2, 9),
      ],
      friends: [
        {
          id: 0,
          name: 'Kent Hutchinson',
        },
        {
          id: 1,
          name: 'Tisha Macias',
        },
        {
          id: 2,
          name: 'Tucker Clemons',
        },
      ],
      greeting: 'Hello, Sara Clark! You have 9 unread messages.',
      favoriteFruit: '_' + Math.random().toString(36).substr(2, 9),
    },
  ];
}
